# Generated by Django 5.0 on 2024-07-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
    ]
