# Generated by Django 5.0.7 on 2024-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='default_subject', max_length=25),
            preserve_default=False,
        ),
    ]
